### ISSUE TITLE
Variable on `parameters.yaml` lacks information regarding possible values

### ISSUE THREAD

**Issue by gruberdev** [handreassa/prenotami#7]
On `parameters.yaml`, you can visualize the following variable, which is the only one that lacks an explanation coupled with its value:
```yaml
marital_status: ""
```

I have never been able to even access the page for signing for an Italian/European passport yet,  so I am not sure which values are valid to be used on this variable. An example or further information would be appreciated, thank you for sharing your code!

**Comment by gabsbelini** [comment]
Let me know if you found the answer for this, I’m about to start using the bot but not sure what to put on it

**Comment by handreassa** [comment]
Guys, will archive this repo due to what I consider to be the right decision based on this here: https://conscuritiba.esteri.it/it/servizi-consolari-e-visti/servizi-per-il-cittadino-italiano/altri-servizi/informativa-sui-servizi-consolari/
Sorry, but I do not encourage automating this processes anymore.
